language: node_js
node_js:
  - 10
  - 12
env:
  - SALTSIZE=256 ENCFUNC=sha512 ITERCOUNT=100000 OUTLENGTH=64 APPNAME="Timesheet Manager" JWTALGO=RS256 JWTSECRET=Secret SESSIONTIMEOUT=1h ROADSHEET_DISTANCE_RATE=0.48
install:
  - npm ci
  - cd server
  - npm ci
  - cd ../client
  - npm ci
  - cd ..
script:
  - cd server
  - npm run lint
  - npm run test
  - cd ../client
  - npm run lint