language: node_js
node_js:
  - 10
  - 12
install:
  - npm install
  - cd node
  - npm install
  - cd ..
script:
  - cd node
  - npm run lint
  - npm test
  - cd ..
env:
  - SALTSIZE=256 ENCFUNC=sha512 ITERCOUNT=100000 OUTLENGTH=64 APPNAME="Timesheet Manager" JWTALGO=RS256 JWTSECRET=Secret SESSIONTIMEOUT=1h ROADSHEET_DISTANCE_RATE=0.48